MergeSortAction.java was implemented
mate-academy/jv-concurrent-merge-sort pull request #46
Opened 2024-05-15 14:48 UTC by katrevichdv

2024-05-16 10:55 UTC, kerrrusha requested changes

2024-05-16 10:55 UTC, kerrrusha commented on src/main/java/mate/academy/MergeSortAction.java
> +        if (array.length < 2) {
magic number

2024-05-16 10:55 UTC, kerrrusha commented on src/main/java/mate/academy/MergeSortAction.java
> +        subSortActions.forEach(MergeSortAction::join);
try to use invokeAll()

2024-05-16 13:21 UTC, MentorMA requested changes

2024-05-16 13:21 UTC, MentorMA commented on src/main/java/mate/academy/MergeSortAction.java
> +        int midIndex = array.length >> 1;
Don`t use bitwise operations

2024-05-16 13:21 UTC, MentorMA commented on src/main/java/mate/academy/MergeSortAction.java
> +        int j = 0;
Bad naming

2024-05-17 11:29 UTC, kerrrusha approved these changes

2025-07-03 13:42 UTC, closed without merging